# Generated by Django 5.1 on 2024-08-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, null=True, unique=True)),
                ('upload_type', models.CharField(max_length=255)),
                ('file_location', models.FileField(null=True, upload_to='media/uploads/originals')),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('bird', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('duration', models.FloatField()),
                ('num_segments', models.IntegerField()),
                ('spectrogram_path', models.FileField(null=True, upload_to='media/spectrograms')),
                ('correct', models.BooleanField(null=True)),
                ('user_bird', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
